//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Mantenimientos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Cars
    {
        [Key]
        public int Car_Id { get; set; }
        public string Car_Brand { get; set; }
        public string Car_Model { get; set; }
        [ForeignKey("Owner_Id")]
        public Nullable<int> Owner_Id { get; set; }
       
        public virtual Owners Owners { get; set; }
    }
}
