//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Mantenimientos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planes
    {
        public int Plane_Id { get; set; }
        public string Plane_Brand { get; set; }
        public string Plane_Model { get; set; }
    }
}
